# Servicios comunes para Chatbot 2.2
# Listo para Traefik
# Voicebot

version: '3.8'

networks:
  private:
  public:


services:
  concordia-ws:
    image: alexanderditzend/concordia-ws:1.0.1
    ports:
      - target: 8646
        published: 3${STACK_CODE-00}46 # concordia tiene que estar conectado a este puerto
        protocol: tcp
        mode: host
    environment:
      - WEB_SOCKET_PORT=8646
      - WAIT_TIME_BETWEEN_MESSAGES=${GATEWAY_WAIT_TIME_BETWEEN_MESSAGES-0.00000000001} # segundos
      - POLLING_INTERVAL=${GATEWAY_POLLING_INTERVAL-500} # milisegundos
      - MODE=${GATEWAY_MODE-DEBUG}
      - LOG_LEVEL=debug
      - BLUEBIRD_W_FORGOTTEN_RETURN=0 
      - RABBITMQ_HOST=${RABBITMQ_HOST-amqp://rabbitmq:5672}
      - BOT_WAKE_UP_WORD=${BOT_WAKE_UP_WORD-/start}
      - PRODUCTION_RASA_SERVICE_NAME=${PRODUCTION_RASA_SERVICE_NAME-rasa}
      - NODE_ENV=production
    networks:
      - private
      - public

  voicebot-api:
    image: alexanderditzend/voicebot-api:1.0.2
    ports:
      - target: 8656
        published: 3${STACK_CODE-00}56 # REST API tiene que pegarle a este puerto
        protocol: tcp
        mode: host  
    environment:
      - LOG_LEVEL=debug
      - BLUEBIRD_W_FORGOTTEN_RETURN=0 
      - RABBITMQ_HOST=${RABBITMQ_HOST-amqp://rabbitmq:5672}
      - BOT_WAKE_UP_WORD=${BOT_WAKE_UP_WORD-/start}
      - PRODUCTION_RASA_SERVICE_NAME=${PRODUCTION_RASA_SERVICE_NAME-rasa}
      - NODE_ENV=production
      - BOT_ENV=production
      - BOT_DEV_URL=http://192.168.43.169:18005
      - NUMBER_CONDENSING_ENABLED=true
    networks:
      - private
      - public
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "3${STACK_CODE-00}72:15672"
      - "3${STACK_CODE-00}73:5672"
    networks:
      - public
      - private
      
       
  
  

      


    



